name: deploy pvf

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull
        uses: actions/checkout@v3 # git pull

      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Cache Node Modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('yarn.lock') }}

      - name: Install Packages
        run: yarn

      - name: Build
        run: yarn build:prod

      - name: Upload
        uses: manyuanrong/setup-ossutil@v2.0
        with:
          endpoint: 'oss-cn-shenzhen.aliyuncs.com'
          access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.ACCESS_KEY_SECRET }}
          # sts-token: 'sts_token'
      - run: ossutil cp -rf dist/ oss://bstu/code/pvf-tools/ -u
